### ISSUE TITLE
Detailed Audit System

### ISSUE THREAD

**Issue by hikalkan** [volosoft/abp#28]
### Functionality

* Log all requests just like in old ABP.
* Log all entity changes just like in old ABP.

### Additional

* logs can be sent to different destinations (like to elastic search...).
* Audit log module will have its own dbcontext and layers.
* Allow to easier contribute to audit logging.

Also investigate this project: https://github.com/thepirat000/Audit.NET

**Comment by hikalkan** [comment]
Closing this. Improvements will be done with separated issues.

**Comment by natiki** [comment]
@hikalkan Is the auditing serviced off a message queue or is it as part of the request. Apologies if there is doco about this and I have not read it or missed it.

**Comment by hikalkan** [comment]
No document yet :)

It's part of the request. However, replacing to a MQ is pretty easy. Just replace the [IAuditingStore](https://github.com/volosoft/abp/blob/master/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/IAuditingStore.cs) interface.
