### ISSUE TITLE
abp-input and abp-dynamic-form should not render label for properties with [HiddenInput] attribute

### ISSUE THREAD

**Issue by hikalkan** [volosoft/abp#324]

**Comment by yekalkan** [comment]
This issue has been fixed already: https://github.com/volosoft/abp/commit/14ab005c6edde6a07cfa7edf58dd341cc3db0349

**Comment by hikalkan** [comment]
Can you also disable validation for hidden inputs.

**Comment by dicksonkimeu** [comment]
Hello,

Am using latest release. 1.0 and am having this issue. Hidden fields are visible.

**Comment by maliming** [comment]
hi @dicksonkimeu Please create an new issue and describe it in detail.
