### ISSUE TITLE
Metronic Tag Helpers

### ISSUE THREAD

**Issue by bbakermmc** [volosoft/abp#349]
Not sure if youve seen this or not:

https://github.com/zdy1988/Zdy.Metronic.TagHelpers

**Comment by hikalkan** [comment]
I didn't know. But we don't intent to create metronic tag helpers. There is also a commerical product for it: https://www.brecons.net/
We are creating a new, extensible, 100% bootstrap compatible theme for ABP. But it need time.

**Comment by bbakermmc** [comment]
@hikalkan why do you guys make custom helpers instead of just using the brecons or any number of other ones?  Are you saying aspnetzero isnt going to be metronic based :P or have a paid metronic theme plugin.

**Comment by hikalkan** [comment]
>why do you guys make custom helpers instead of just using the brecons or any number of other ones

To be clear, we will never create Metronic specific tag helpers.
