### ISSUE TITLE
ILifetimeDependency or ILifetime?

### ISSUE THREAD

**Issue by hitaspdotnet** [volosoft/abp#350]
* ``ITransient`` to register with transient lifetime.
* ``ISingleton`` to register with singleton lifetime.

What's the namespace of type ISingleton? Is it ISingletonDependency?

**Comment by hitaspdotnet** [comment]
Because I use translator I mis sample code, Sorry.
But `ILifetimeDependency` in [docs](https://github.com/volosoft/abp/blob/master/docs/Dependency-Injection.md#dependency-interfaces) is better

**Comment by hikalkan** [comment]
Sorry for the documentation. Will fix it.

**Comment by hikalkan** [comment]
done: https://github.com/volosoft/abp/commit/0b02ae0630a902d82a9947e80daf5b86f004b6a2
