### ISSUE TITLE
UI suggestion : Save and continue editing

### ISSUE THREAD

**Issue by hitaspdotnet** [volosoft/abp#352]
In some forms where the current entity has related data in separate module we need save before continue to get just created entityID.
Isn't important but makes more extensible. As example in tenant management when our feature management is separate module (micro-service in future) we need to have 2 api calls.

**Comment by hitaspdotnet** [comment]
I think is possible by new razor pages and OnPost's APIs, so we need a TagHelper for skip closing modal after submit.

**Comment by hikalkan** [comment]
I could not understand what we can implement in the framework for that. This is a use case specific and implemented in the application level.

For your example, I would design feature selection as a separate modal for a tenant. We designed it like that for permission selection for a user/role.
So, we save the user then select "manage permissions" action to select permissions.

**Comment by hitaspdotnet** [comment]
@hikalkan It's about building helpful Taghelpers library from ABP. I must change my example to wizard forms. Is there any plan to implement integration of the Wizard Forms in UI library?

**Comment by hikalkan** [comment]
>Is there any plan to implement integration of the Wizard Forms

Wizards are UI level stuff and we can create Wizard UI components in the future. That's OK. But implementation is not simple if you expect a server-intergated system.
For instance, a wizard may store all data in the client side and post as a single request, while another wizard may want to save state in the server, while another one may want to remember the step (if user closes the browser in an intermediate state) for a specific unit of time, even another one may decide some steps are optional (and the process is completed without filling the optional steps), while others may need to perform other tasks.
