### ISSUE TITLE
Build failed for tenant management module

### ISSUE THREAD

**Issue by hitaspdotnet** [volosoft/abp#360]
`Volo\Abp\TenantManagement\TenantConnectionString.cs(7,18): 
error CS0534: 'TenantConnectionString' does not implement inherited abstract member 'Entity.GetKeys()'`

**Comment by yekalkan** [comment]
This is the breaking-change that causes this issue https://github.com/volosoft/abp/commit/a1af5081aaea1b0faa36317fd33287e04561340e
