### ISSUE TITLE
DependencyResolutionException 

### ISSUE THREAD

**Issue by tangname** [volosoft/abp#361]
As ASP.NET Core MVC Tutorial - Part II，when I click the Add button,it occur an exception:
`DependencyResolutionException: No constructors on type 'Acme.BookStore.Books.BookAppService' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'`

I check the  previous code and the only differences  are _IBookAppService_ and _BookAppService_  that I used  _Acme.BookStore.Books_ namespace。

Should  I  use the  project namespace (i.e., Acme.BookStore) in AppService necessarily?
I can't add other namespaces.

thanks in advance for your help!

**Comment by hikalkan** [comment]
Your BookAppService is probably not registered to dependency injection. Did you inherit IBookAppService from IApplicationService?

**Comment by tangname** [comment]
yeah.as same as the tutorial demo,my _IBookAppService_  inherit _IAsyncCrudAppService_ ,
i see the IAsyncCrudAppService is inherit  IApplicationService.
the only difference is my IBookAppService's namespace is _Acme.BookStore.Books_ not Acme.BookStore.

i try to remove the Books namespace and use  _Acme.BookStore_ ,it works very well.

that what i don't understand.

**Comment by hikalkan** [comment]
Namespace should not change the result. I will try with the "Acme.BookStore.Books" namespace.

**Comment by hikalkan** [comment]
I did it and just worked as expected: https://github.com/volosoft/abp/compare/issue-361

Download this branch to see its working: https://github.com/volosoft/abp/tree/issue-361
