### ISSUE TITLE
Make containers a priority by adding 1st class support for....

### ISSUE THREAD

**Issue by natiki** [volosoft/abp#370]
Hi Halil,

These feature requests come as I look to use ABP .NET Core with Kubernetes and Docker. Some overlap with what I have already requested over in the ABP Repo. 

- Bare bones template so that a simplistic .NET Core micro service with a basic web api can be easily spun up. Yes I know this can be done by taking a core SPA template. Taking out the Vue.js integration etc. but this is painful. I have posted in the other repo a list of your requirements for possible inclusion as I have to do a few of these.
- **Message Queue:** I know RabbitMQ is planned but an abstraction similair to [Rebus](https://github.com/rebus-org/Rebus). Means moving to something like Azure Service bus becomes painless etc.
- Support for **additional Linux databases** as first class targets. Most people will be deploying to Linux containers and very few will be running SQL Server on Linux.
   - PostgreSQL
   - mySQL
   - CockroachDB (https://www.cockroachlabs.com). This is particularly interesting as it is ultimately a SQL front end to etcd.
- **API Gateway** (Ocelot or similair) integration. This would address my long standing request for rate limiting etc. from the public repo as well.

As always appreciate the opportunity to make requests such as the above.

**Comment by hikalkan** [comment]
We can create a microservice startup template. I will give high priority to this: https://github.com/volosoft/abp/issues/377

For Rebus, I created an issue: https://github.com/volosoft/abp/issues/376
I will check it.

We are developing EF Core integration and modules as DBMS independent. So, it will be straightforward to change SQL Server to others. We can create tutorials for that.

We will work on API Gateway, sure: https://github.com/volosoft/abp/issues/163
I don't know Ocelot yet, but will learn :)

**Comment by natiki** [comment]
DBMS - As long as key generation works (https://github.com/volosoft/abp/issues/328) all should be good. I will close that case as soon as I have read up on the alternative to HiLo.
