### ISSUE TITLE
Angular: Moving to Reactive (and Dynamic) Forms

### ISSUE THREAD

**Issue by leonkosak** [volosoft/abp#381]
http://jasonwatmore.com/post/2018/05/10/angular-6-reactive-forms-validation-example
https://juristr.com/blog/2017/10/demystify-dynamic-angular-forms/

Even relatively simple forms for adding (editing) users,... are pretty messy, because logic is in html (no strongly typed in typescript files, no unit testing,...).
Consider this when rewriting ABP and Zero (https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3488#issuecomment-396199878).

**Comment by hikalkan** [comment]
Thank you for your suggestion. I have taken this as a note and will consider while developing the angular template. Closing this.
