### ISSUE TITLE
User manual (documentation)

### ISSUE THREAD

**Issue by leonkosak** [volosoft/abp#383]
Versioned documentation (user manual). Something like Read the Docs (https://readthedocs.org/), but that is not hosted separately (future-proof and independent solution).
In my opinion, it's better to write user manual in an application framework (and committed to Git/TFS/...) and if needed to be exported to Docx/PDF.
Not many IT department has great documentation systems and user manual is always messy and incomplete.

A user has to have an option to find information fast.

**Comment by hikalkan** [comment]
We are building a "docs" module for that purpose: https://github.com/volosoft/abp/tree/master/modules/docs

This module will be a module that can be embedded into any application. We will use it for the ABP documentation first (like https://aspnetboilerplate.com/Pages/Documents).
