### ISSUE TITLE
Create .NET Core templates

### ISSUE THREAD

**Issue by Trojaner25** [volosoft/abp#387]
`dotnet new` supports project templates:
https://github.com/dotnet/templating/

These templates can have various settings: you can include / exclude regions and process style statements with command line switches. It also supports renaming operations (i.e. renaming projects and placeholder values). 

This would be much convient than having to download it from the website.

**Comment by hikalkan** [comment]
Thank you for your suggestion. However, we are very flexible in our project creation system and don't want to be restricted by another tooling.
