### ISSUE TITLE
Motivation of Abp

### ISSUE THREAD

**Issue by AlexSenchenko** [volosoft/abp#388]
Hi 
Was really surprised to see next gen of Abp framework.
Can you please explain the motivation of creating next version of Abp framework?

**Comment by hitaspdotnet** [comment]
Hi, Welcome to ABP vNext 💥 💥 :P :)
I think you can find your solution at Mr @hikalkan [comment](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3488#issuecomment-396199878)

**Comment by hikalkan** [comment]
Thank @hitaspdotnet.

In addition, I will publish a long blog post to explain it (when? soon!).
