### ISSUE TITLE
BackgroundJobs.TestBase build failed

### ISSUE THREAD

**Issue by hitaspdotnet** [volosoft/abp#392]
https://github.com/volosoft/abp/blob/3c87b72d754740579fff007e493e08426ff1806f/modules/background-jobs/test/Volo.Abp.BackgroundJobs.TestBase/Volo.Abp/BackgroundJobs/BackgroundJobsTestBaseModule.cs#L18

> error CS1061: 'BackgroundJobOptions' does not contain a definition for 'IsEnabled' and no extension method
 'IsEnabled' accepting a first argument of type 'BackgroundJobOptions' could be found (are you missing a using directive or an assembly reference?)

**Comment by hitaspdotnet** [comment]
@hikalkan Is it must be `IsJobExecutionEnabled` ?

**Comment by hikalkan** [comment]
Thanks. Fixed.
