### ISSUE TITLE
Remove unnecessary [Display] attributes

### ISSUE THREAD

**Issue by hikalkan** [volosoft/abp#398]
ABP now automatically localize view model properties with their name. So, no need to add `[Display(Name="Password")]` for a property named `Password`.

We should apply this for;

- [x] Modules
- [x] Samples
- [x] Tutorials

I implemented it for the Identity module:

https://github.com/volosoft/abp/commit/2fa6679fc59c9128dfb42b0c6b84d0cf1f5b7cd4

**Comment by bbakermmc** [comment]
@hikalkan Is this configurable?  We don't use multi language, and maintaining the code in the current XML/JSON format isn't conducive to using template generation.  If we use Display does it override whats in the XML/JSON or will it show the dumb {DISPLAY_TEXT} because we didn't define it there?

**Comment by hikalkan** [comment]
>If we use Display does it override whats in the XML/JSON

Yes. Also, if you don't use localization (json files) or didn't define the name in the localization file then there is no difference from the default behaviour. So, it's backward compatible by it's nature.
